### ISSUE TITLE
Bi-Weekly Scrum - [Mar 6 - Mar 20]

### ISSUE THREAD

**Issue by blessingomotayo** [arungalva/4th-year-Project-Website#55]
Provides a platform for each team member to add comments with their own contributions.
Questions to be answered:

what have I done this week?
what will I do next week?
what is holding me back? (if applicable)
Each can be 1-2 sentences in length

Must be done before the end date.

**Comment by ShasRanasinghe** [comment]
**what have I done this week?**

- Fixed a bug where the professor page was not displaying the projects in the database upon first visiting the page
- Enabled the /projects page to display all available projects
- Changed the /addProjects to /project/add.
- The above change also caused issues with the stylesheets so the path needed to be changed to a relative path to handle this
- Added the ability to add program restrictions to a project when its created

**what will I do next week?**

- Fix a bug where the program restrictions of a project are being added to the join table, however, they cannot be retrieved through the project which causes a LazyInitializationException
- Assist with implementing user login

**what is holding me back?**

- I faced a large delay this week while trying to implement program restrictions. There was no consensus on the best way to do it so i attempted both to see which would work. I faced errors with the database and entity managers for both methods. Eventually, after the master was successfully switched from SQLite to Postgres i was able to get one of the methods implements but with a small issue that i have mentioned above.

**Comment by seanrt** [comment]
**what have I done this week?**

- Added the edit projects feature
- Fixed the broken project tests
- Fixed the addprojects page not redirecting to the professor page
- Cleaned up a bunch of code

**what will I do next week?**

- Get student registration working

**what is holding me back?**

- We had very little time this past milestone. In week 1, we had 2 midterms and 2 4th year project deliverables. This past week, we had our 4th year project poster fair and a project milestone in another course. It's not really an excuse but I guess I thought I'd have more time to allocate to this project than I did. I will try to better manage my time for the next milestone.

**Comment by blessingomotayo** [comment]
**what have I done this week?**

- Created a controller to archive a project which also fixed the bug regarding the archive button not working
- Made the logo redirect to the home page and remove the home page in the naw bar
- Removed the student column in professor view and project view until student functionality has been created
- Removed the static content and buttons that do not work and added TODO in the code to show that they will need to be done for next sprint
- Added tests for the archive button

**what will I do next week?**

- I will create a student view and a controller for it
- I will allow the professor to undo an archive on a project

**what is holding me back?**
- Busy week with 4th year project poster fair
- The SqLite caused a few problems while I was creating the archive function

**Comment by arungalva** [comment]
**what have I done this week?**

- Finally got Postgres working on Heorku
- Refactored code to remove the use of entitymanager
- Wrote Professor service and re-wrote the tests and code to use repositories

**what will I do next week?**

- Fix a couple of bugs in the front-end
- I will also be working on authentication and authorization
- Prepare for the presentation on Monday

**what is holding me back?**
- 4th year project took up a lot of time last week and hence we weren't able to push too many features but now its out of the way, we should be able to make a lot of progress for the next iteration
- sqLite was not working too well and setting up Postgres was quite challenging initially. This was because, we were using entitymanager in our code and needed to use persistence.xml file. I wasn't user how to pass in environment variables in persistence.xml so that heroku can inject its credentails. Once I rewrote the code to use repositories, it was really easy to switch to Postgres
