### ISSUE TITLE
Weekly Scrum - [Feb 24 - Mar 2]

### ISSUE THREAD

**Issue by blessingomotayo** [arungalva/4th-year-Project-Website#6]
Provides a platform for each team member to add comments with their own contributions.
Questions to be answered:
 - what have I done this week?
- what will I do next week?
- what is holding me back? (if applicable)

Each can be 1-2 sentences in length

**_Must be done before the end date._**

**Comment by ShasRanasinghe** [comment]
What have I done this week?
- Set up Travis CI and Heroku to work with the application
- Added the team as collaborators on heroku
- Created a very basic add project form that send a post request and adds the project to the database
- Created tests that ensure the form pages load correctly
- Created tests that ensure the post request does in fact add a project entitiy to the DB
- The Database was being cleared upon restart of the application so I manged to make sure all data is persisted through restarts
- Running the tests were also clearning the database as they were initially made when the DB was being cleared on restarts. Fixed that so the tests only deleted the entities it created and leaves everything else untouched

What will I do next week?
- I plan on implementing the edit project functionality
- Create more through tests to ensure the bugs that got past us this milestone will not get past us again
- Use repositories instead of entity managers
- Assist in assing features to the student view

What is holding me back?
- I had a hard time installing and getting a MySQL server running on my computer which wasted some time.

**Comment by blessingomotayo** [comment]
**What have I done this week?**
- I added a reviewers 'To Do List' in the pull request template. That way the person creating the PR can tick or write new steps they need the reviewer to double check before approving the PR; added the concept of ToHat.
- Created the header and footer html pages as fragments that were included in each view on the front-end.
- Created the home view at end point '/' with a reference button to the professor view.
- Added to the home view course outline, deadlines, announcements and projects sections from the navigation bar.
- Created tests that ensure these pages loaded correctly
- Created a few issues related to the changes I made

**What will I do next week?**
- I plan to start the student view and have it connected to the controller and the DB
- I also would like to work on the issues I created that are related to the front-end

**What is holding me back?**
- Had a bit of a hard time trying to add the fragments to the views on the front-end, which took a little bit of time.
- When it came time to need a DB, I had a little trouble setting up mySQL on my computer.

**Comment by arungalva** [comment]
**What have I done this week?**
- Set up Review and Issue templates
- Setup travis CI badge
- Created the professor view
- Changed the look of the add new project view
- Created a few issues about the project
- Debugged and fixed database issues with heroku (Reverted to sqlite for now)

**What will I do next week?**
- Setup multiple databases (testing and prod) and setup hreoku with postgres
- I will be working on some of the backend controllers (authentication and authorization)
- I will go back and write automated tests for the /professor view and add new project view

**What is holding me back?**
- Had a lot of trouble with mysql on heroku. Got a max connection error but couldn't figure it out. Reverted back to sqlite for now

**Comment by seanrt** [comment]
**What have I done this week?**
- Created the User entity class
- Created the Project entity class
- Set up the MySql configuration
- Wrote unit tests for persisting the User and Project entities
- Wrote up the basic README

**What will I do next week?**
- Work on moving from EntityManager to EntityRepositories #
- Add more unit tests for persisting entities #46 
- Help with developing the login/authentication view
- Work on the controller for searching projects
- Work on the controller for editing projects

**What is holding me back?**
- Had a lot of trouble getting the persistence of entities to work. I went with MySql over Sqlite because Sqlite wouldn't work on my machine.
- This past week has been our most busy week of the semester. It was difficult to allocate enough time to work on this project. We will have much more time for next iteration.

**Comment by ShasRanasinghe** [comment]
Scrum completed
